### ISSUE TITLE
Material UI setup

### ISSUE THREAD

**Issue by rollyar** [astrocket/react-rails-template#3]
Hello tanks for you template, can't setup/run sample with material UI, how i can make to run?

When try a rails g react users index, files are generated ok.
Can start with rails s
But when call to localhost:3000/home/index the next errors appears:
 
ERROR in ./app/javascript/components/users/Index.jsx
Module not found: Error: Can't resolve 'antd' in '/Users/tony/siteProject/new/blog/app/javascript/components/home'
 @ ./app/javascript/components/home/Index.jsx 13:0-14
 @ ./app/javascript/components ^\.\/.*$
 @ ./app/javascript/packs/application.js

Completed 500 Internal Server Error in 36328ms (ActiveRecord: 0.0ms)

ExecJS::ProgramError - Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.:
  app/controllers/application_controller.rb:10:in `to_react'
  app/controllers/users_controller.rb:8:in `index'

How i cant resolve this, can you show me some example, Tanks!!

**Comment by astrocket** [comment]
@rollyar Hi there.
I found that there were some bugs with asking user's input design option.
If you just want a quick fix go to lib/generators/react/templates/pages.js.erb and chante 'antd' to '@material-ui/core'

I will also update the source code soon though.
